# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    ecb.url: 'http://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml'
    cbr.url: 'https://www.cbr-xml-daily.ru/daily_json.js'
    currency_provider.ordering:
        - 'ecb'
        - 'cbr'

services:
    App\Controller\CurrencyController:
        public: true
        arguments:
            - "@app.service.chain_currency_provider"
        calls:
            - ['setContainer', ['@service_container']]

    app.service.chain_currency_provider:
        class: App\Service\ChainCurrencyProvider
        arguments:
            - '%currency_provider.ordering%'

    app.service.ecb_currency_provider:
        class: App\Service\EcbCurrencyProvider
        tags:
            - { name: 'app.currency_provider', alias: 'ecb' }
        arguments:
            - '%ecb.url%'

    app.service.cbr_currency_provider:
        class: App\Service\CbrCurrencyProvider
        tags:
            - { name: 'app.currency_provider', alias: 'cbr' }
        arguments:
            - '%cbr.url%'